spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: a4006ed0c83cfbf02f9f167bb3fe7651
  mail:
    password: NEED_TO_INPUT
custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUser:
              oauthId: oauthId
              nickname: nickname